# Generated by Django 3.1.2 on 2020-10-11 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='titulo',
            options={'verbose_name': 'Titulo', 'verbose_name_plural': 'Titulos'},
        ),
        migrations.DeleteModel(
            name='Empleador',
        ),
        migrations.AddField(
            model_name='empleado',
            name='ciudad_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_empleado', to='compania.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='titulo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_empleado', to='compania.titulo', verbose_name='Titulo'),
        ),
    ]
